Issue #44: Resolve (most remaining) Solaris issues
Only one final issue remains, setecho/noecho/waitnoecho still has
calls to tcgetattr(master_fd) which causes a failure on Solaris.
Remaining work:

- catch and decorate these exceptions with "not possible on your
  platform."

- as a workaround, provide echo=True/False to spawn().

- document the inability to hide passwords from password prompts and the
  like somewhere in the documentation. Recommend to use echo=False on
  such platforms, and not to depend on waitnoecho() for such prompts.

Example remaining failing test case:

======================================================================
ERROR: test_expect_echo_exact (test_unicode.UnicodeTests)
Like test_expect_echo(), but using expect_exact().
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/zones/pexpect/pexpect/tests/test_unicode.py", line 48, in test_expect_echo_exact
    self._expect_echo(p)
  File "/zones/pexpect/pexpect/tests/test_unicode.py", line 56, in _expect_echo
    p.setecho(0) # Turn off tty echo
  File "/zones/pexpect/pexpect/pexpect/__init__.py", line 997, in setecho
    attr = termios.tcgetattr(self.child_fd)
error: (22, 'Invalid argument')